# Generated by Django 2.0.7 on 2018-08-06 19:03

import ckeditor.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompaniesCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_amount', models.IntegerField()),
                ('max_amount', models.IntegerField()),
                ('min_days', models.IntegerField()),
                ('max_days', models.IntegerField()),
                ('miscs', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='CompaniesInstallment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inst_name', models.CharField(max_length=100)),
                ('inst_min_amount', models.IntegerField()),
                ('inst_max_amount', models.IntegerField()),
                ('inst_min_duration', models.IntegerField()),
                ('inst_max_duration', models.IntegerField()),
                ('inst_first_free', models.BooleanField()),
                ('inst_amount_first_free', models.IntegerField()),
                ('inst_age', models.CharField(max_length=100)),
                ('inst_verification', models.CharField(max_length=100)),
                ('inst_miscs', models.CharField(blank=True, max_length=250)),
                ('inst_example_amount', models.IntegerField()),
                ('inst_example_duration', models.IntegerField()),
                ('inst_example_fixed_interest_rate', models.IntegerField()),
                ('inst_example_total_amount_repay', models.IntegerField()),
                ('inst_example_total_installment_amount', models.IntegerField()),
                ('inst_example_capital_interest', models.IntegerField()),
                ('inst_example_provision', models.IntegerField()),
                ('inst_example_rrso', models.IntegerField()),
                ('inst_example_installment_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CompaniesLoans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_amount', models.IntegerField()),
                ('max_amount', models.IntegerField()),
                ('min_duration', models.IntegerField()),
                ('max_duration', models.IntegerField()),
                ('first_free', models.BooleanField()),
                ('amount_first_free', models.IntegerField()),
                ('age', models.CharField(max_length=100)),
                ('verification', models.CharField(max_length=100)),
                ('miscs', models.CharField(blank=True, max_length=250)),
                ('example_amount', models.IntegerField()),
                ('example_duration', models.IntegerField()),
                ('example_fixed_interest_rate', models.IntegerField()),
                ('example_total_amount_repay', models.IntegerField()),
                ('example_total_installment_amount', models.IntegerField()),
                ('example_capital_interest', models.IntegerField()),
                ('example_provision', models.IntegerField()),
                ('example_rrso', models.IntegerField()),
                ('example_installment_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('published_date', models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 6, 19, 3, 1, 520357, tzinfo=utc), null=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('meta_title', models.CharField(max_length=158)),
                ('meta_description', models.CharField(max_length=320)),
                ('slug', models.SlugField(default='')),
            ],
        ),
    ]
