# Generated by Django 2.0.7 on 2018-08-06 19:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 6, 19, 3, 17, 357189, tzinfo=utc), null=True),
        ),
    ]
