# Generated by Django 2.0.7 on 2018-08-07 17:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180807_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 7, 17, 46, 11, 981428, tzinfo=utc), null=True),
        ),
    ]
