# Generated by Django 2.0.7 on 2018-07-25 20:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180725_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 7, 25, 20, 2, 16, 999331, tzinfo=utc), null=True),
        ),
    ]
