# Generated by Django 2.0.7 on 2018-08-01 18:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180731_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 1, 18, 51, 38, 384182, tzinfo=utc), null=True),
        ),
    ]
