# Generated by Django 2.0.7 on 2018-08-01 19:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180801_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 1, 19, 17, 53, 206534, tzinfo=utc), null=True),
        ),
    ]
